// <auto-generated />
using CuaHangHoaQua.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHangHoaQua.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CuaHangHoaQua.Models.LoaiThucPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.LoaiThucPham_ThucPham", b =>
                {
                    b.Property<int>("LoaiThucPhamId")
                        .HasColumnType("int");

                    b.Property<int>("ThucPhamId")
                        .HasColumnType("int");

                    b.HasKey("LoaiThucPhamId", "ThucPhamId");

                    b.HasIndex("ThucPhamId");

                    b.ToTable("LoaiThucPham_ThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ThucPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ViTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViTris");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ViTri_ThucPham", b =>
                {
                    b.Property<int>("ViTriId")
                        .HasColumnType("int");

                    b.Property<int>("ThucPhamId")
                        .HasColumnType("int");

                    b.HasKey("ViTriId", "ThucPhamId");

                    b.HasIndex("ThucPhamId");

                    b.ToTable("ViTri_ThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.LoaiThucPham_ThucPham", b =>
                {
                    b.HasOne("CuaHangHoaQua.Models.LoaiThucPham", "LoaiThucPham")
                        .WithMany("loaiThucPham_ThucPhams")
                        .HasForeignKey("LoaiThucPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangHoaQua.Models.ThucPham", "ThucPham")
                        .WithMany("loaiThucPham_ThucPhams")
                        .HasForeignKey("ThucPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiThucPham");

                    b.Navigation("ThucPham");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ViTri_ThucPham", b =>
                {
                    b.HasOne("CuaHangHoaQua.Models.ThucPham", "ThucPham")
                        .WithMany("viTri_ThucPhams")
                        .HasForeignKey("ThucPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CuaHangHoaQua.Models.ViTri", "ViTri")
                        .WithMany("viTri_ThucPhams")
                        .HasForeignKey("ViTriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThucPham");

                    b.Navigation("ViTri");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.LoaiThucPham", b =>
                {
                    b.Navigation("loaiThucPham_ThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ThucPham", b =>
                {
                    b.Navigation("loaiThucPham_ThucPhams");

                    b.Navigation("viTri_ThucPhams");
                });

            modelBuilder.Entity("CuaHangHoaQua.Models.ViTri", b =>
                {
                    b.Navigation("viTri_ThucPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
